#!/bin/bash

ERROR=false
syncderp=false
synckernel=false
poweroff=false
root=false
device=""
jobs=""
start_time=`date`

android_version="bp2a"
derp_repo="https://github.com/DerpFest-AOSP/"
derp_branch="16"
los_branch="lineage-23.0"
los_repo="https://github.com/LineageOS/"
local_manifest_url="git@github.com:SeanDabes/derp_local_manifest_p7.git"

local_manifest_folder="derp_local_manifest_p7"
local_manifest_file="$local_manifest_folder/roomservice_seandabes.xml"
rootfolder=`pwd`
toolsfolder="$rootfolder/tools"
banner_script="$toolsfolder/banner.sh"
monitor_script="$toolsfolder/monitor.sh"
derpfestfolder="$rootfolder/../derpfest" # Change for own one
out_rom_folder="$derpfestfolder/00_latest_builds/"

debloatmkfile="$derpfestfolder/vendor/google/gms/gms-vendor.mk"
debloatmkfilebkp="$debloatmkfile.bak"
debloatbpfile="$derpfestfolder/vendor/google/gms/Android.bp"
debloatbpfilebkp="$debloatbpfile.bak"

# Terminal Colors
readonly BLUE='\033[1;34m'
readonly GREEN='\033[1;32m'
readonly YELLOW='\033[1;33m'
readonly RED='\033[1;31m'
readonly CYAN='\033[1;36m'
readonly MAGENTA='\033[1;35m'
readonly GRAY='\033[1;90m'
readonly WHITE='\033[1;37m'
readonly NOCOLOR='\033[0m'
readonly BOLD='\033[1m'
readonly DIM='\033[2m'
readonly WHITEONBLUE='\033[1;37;44m'
readonly WHITEONMAGENTA='\033[1;37;45m'
readonly WHITEONYELLOW='\033[1;37;43m'
readonly WHITEONCYAN='\033[1;37;46m'
readonly WHITEONRED='\033[1;37;41m'
colors=("$BLUE" "$GREEN" "$YELLOW" "$RED" "$CYAN" "$MAGENTA" "$GRAY" "$WHITE")

chmod +x $banner_script
chmod +x $monitor_script

SECONDS=0 # Timer start

function gcam() { # Change Google Camera for GCam by BSG
    banner
    echo -e "${WHITEONBLUE} MOD: GCAM by BSG                  ${NOCOLOR}"
    echo
    echo "- Checking Google Camera..."
    local camerafolder="$derpfestfolder/vendor/google/camera/proprietary/product/priv-app/GoogleCamera"
    local camerafile="GoogleCamera.apk"
    local bsgcamera="MG9.4.103_V20_MGC.apk"
    local gcamhash="f64522e646e8cbebe503a5ce1eefb60e1596ae45fa5732dfc5f3569d717c91fb"
    if [ ! -f "$camerafolder/$camerafile" ] || [ $(sha256sum "$camerafolder/$camerafile" | cut -d ' ' -f 1) != $gcamhash ]; then
        echo -e "${YELLOW} Gcam not found${NOCOLOR}"
        echo
        echo "- Checking ROM tree..."
        for file in `find | grep $camerafile`; do
            echo $file
            rm $file
        done
        if [ -f $bsgcamera ]; then rm $bsgcamera; fi
        echo "Downloading GCAM from celzoazevedo.com..."
        wget -nv --show-progress https://1-dontsharethislink.celsoazevedo.com/file/filesc/$bsgcamera
        echo "Checking hash..."
        if [ $(sha256sum $bsgcamera | cut -d ' ' -f 1) = $gcamhash ]; then
            echo -e "${GREEN}Cam OK${NOCOLOR}"
            echo "Copying to ROM tree..."
            mv $bsgcamera "$camerafolder/$camerafile"
        else
            echo "Couldn't download!!"
        fi
    else
        echo -e "${GREEN}GCAM from BSG found${NOCOLOR}"
    fi
    sleep 3
}

function wait_task(){
    local marquee_anim=(
        '▕                    ▏'
        '▕▒                   ▏'
        '▕▒▒                  ▏'
        '▕▒▒▒                 ▏'
        '▕ ▒▒▒                ▏'
        '▕  ▒▒▒               ▏'
        '▕   ▒▒▒              ▏'
        '▕    ▒▒▒             ▏'
        '▕     ▒▒▒            ▏'
        '▕      ▒▒▒           ▏'
        '▕       ▒▒▒          ▏'
        '▕        ▒▒▒         ▏'
        '▕         ▒▒▒        ▏'
        '▕          ▒▒▒       ▏'
        '▕           ▒▒▒      ▏'
        '▕            ▒▒▒     ▏'
        '▕             ▒▒▒    ▏'
        '▕              ▒▒▒   ▏'
        '▕               ▒▒▒  ▏'
        '▕                ▒▒▒ ▏'
        '▕                 ▒▒▒▏'
        '▕                  ▒▒▏'
        '▕                   ▒▏'
        )
    while [ ! -f /tmp/end_task ]; do
        for i in "${marquee_anim[@]}" ; do
            printf "\r%s %s" "$i"
            sleep 0.1
        done
    done

    echo -e "\n"
}

function builddevice() {
    bash $banner_script nowait $1 $android_version $los_branch
    cd $derpfestfolder

    export KERNEL_MANIFEST_BRANCH=$los_branch
    export KERNEL_MANIFEST_REMOTE=$los_repo

    #TMUX-SESSION-----------------------
    tmux new-session -d -s derp_session
    tmux split-window -v
    tmux split-window -h -t 0
    tmux resize-pane -t 2 -U 40
    tmux split-window -v -t 2
    tmux resize-pane -t 3 -D 30
    tmux select-pane -t 2
    tmux send-keys -t 0 "bash $banner_script wait $1 $android_version $los_branch; echo 'Process started at `date`'" C-m
    tmux send-keys -t 1 "clear; echo; echo -e '${WHITEONMAGENTA} Building ROM with $jobs simultaneous processes... ${NOCOLOR}'; echo; bash -c '$(declare -f wait_task); wait_task'" C-m
    tmux send-keys -t 2 "clear; . build/envsetup.sh && lunch lineage_$1-$android_version-user &&  mka derp -j $jobs; touch /tmp/end_task" C-m
#     tmux send-keys -t 3 "htop -p --readonly" C-m
    tmux send-keys -t 3 "bash $monitor_script" C-m
    tmux send-keys -t 1 "clear; echo; echo -e ' ${BLUE}Cooling down...${NOCOLOR}'; sleep 5; rm /tmp/end_task; tmux kill-session -t derp_session" C-m

    tmux attach-session -t derp_session

    #TMUX-SESSION-END-------------------

    # Move files to more accessible folder
    local srcfolder="out/target/product/$1/"
    local endfolder="$out_rom_folder$1/"
    mkdir -p $endfolder
    local files=(DerpFest*.zip DerpFest*.sha256sum boot.img dtbo.img init_boot.img vendor_boot.img vendor_kernel_boot.img)
    for item in "${files[@]}"; do
        if [ -f $srcfolder$item ]; then
            mv $srcfolder$item $endfolder
        else
            ERROR=true
        fi
    done

    sleep 5
    echo
}

function rootdevice(){
    bash $banner_script nowait $1 $android_version $los_branch
    echo -e "${WHITEONBLUE} Rooting: $1                       ${NOCOLOR}"
    cd $derpfestfolder/00_latest_builds/$1/
    if [ ! -f boot.img ]; then
        echo -e "${RED}.img not found for $1${NOCOLOR}"
        return
    fi

    local rootfolder=`pwd`"/root"
    if [ -d "$rootfolder" ]; then rm -rf "$rootfolder"; fi
    mkdir $rootfolder
    cd $rootfolder

    echo
    echo "Getting magiskboot..."
    curl -s https://api.github.com/repos/topjohnwu/magisk/releases/latest | grep "browser_download_url.*apk" | cut -d : -f 2,3 | tr -d \" | wget -qi -
    unzip Magisk*.apk lib/x86_64/libmagiskboot.so
    mv $(find | grep libmagiskboot.so) magiskboot
    rm -rf lib
    rm *.apk
    chmod +x magiskboot

    echo
    echo "Getting Sultan Wild Kernel..."
    curl -s https://api.github.com/repos/WildKernels/Sultan_KernelSU_SUSFS/releases/latest | grep "browser_download_url.*gs201" | cut -d : -f 2,3 | tr -d \" | wget -qi -
    sultanfile="$(ls *gs201*WKSU*.zip)"
    if [ -f $sultanfile ]; then
        unzip $sultanfile Image.lz4
    else
        echo "Sultan Wild Kernel not found. Download it and try again"
        return
    fi

    echo
    echo "Unpacking original boot.img..."
    cp ../boot.img boot.img
    ./magiskboot unpack boot.img
    echo
    echo "Modifying kernel..."
    mv -f Image.lz4 kernel
    echo
    echo "Repacking kernel..."
    ./magiskboot repack boot.img
    mv new-boot.img boot_$1_WKSU_SUSFS.img
    rm kernel magiskboot $sultanfile boot.img

    echo
    echo "Getting Sultan Wild root manager..."
    curl -s https://api.github.com/repos/WildKernels/Wild_KSU/releases/latest | grep "browser_download_url" | cut -d : -f 2,3 | tr -d \" | wget -qi -
}

function rmlines(){ # file, key_pattern, end_pattern
    local tempfile="temp.bp"
    local line_number1=0
    local line_number2=0
    local line_number3=0
    local found_line1=0
    local found_line2=0
    local start=0
    local end=0

    while IFS= read -r line; do
        line_number1=$((line_number1 + 1))

        if [[ "$line" == *"$2"* ]]; then
            found_line1=$line_number1
            break
        fi
    done < "$1"

    while IFS= read -r line; do
        line_number2=$((line_number2 + 1))

        if [[ "$line" == *"$3"* ]]; then
            if [ "$line_number2" -lt "$found_line1" ]; then
                continue
            else
                found_line2=$line_number2
                break
            fi
        fi
    done < "$1"

    start=$(($found_line1 - 1))
    end=$(($found_line2 - 1))

    line_number=0

    while IFS= read -r line; do
        line_number3=$((line_number3 + 1))

        if (( line_number3 < start || line_number3 > end )); then
            echo "$line" >> "$tempfile"
        fi
    done < "$1"

    mv "$tempfile" "$1"
}

function debloat(){
    echo -e "${WHITEONBLUE} Debloating...                     ${NOCOLOR}"
    cp "$debloatmkfile" "$debloatmkfilebkp"
    cp "$debloatbpfile" "$debloatbpfilebkp"
    local debloatfiles=(        # Comment to keep in ROM
        #GoogleExtShared
        GooglePrintRecommendationService
        #GooglePackageInstaller
        TagGoogle
        CalculatorGoogle
        CalendarGoogle
        #Chrome64
        Drive
        Gemini
        Gmail2
        #GoogleContacts
        GoogleLocationHistory
        #LatinImeGoogle
        Maps
        Photos
        #SpeechServicesByGoogle
        #TrichromeLibrary64
        #WebViewGoogle64
        YouTube
        talkback
        #AndroidAutoStub
        #ConfigUpdater
        #CrossDeviceServices
        #DeskClockGoogle
        FamilyLinkParentalControls
        #FilesGoogle
        #GWP
        #GmsCore
        #AndroidPlatformServices
        #GoogleDialer
        #GoogleOneTimeInitializer
        #GooglePartnerSetup
        #GoogleRestore
        #Messages
        PersonalSafety
        #Phonesky
        #Turbo
        #Velvet
        Wellbeing
        EmergencyInfoGms
        GoogleFeedback
        #GoogleServicesFramework
        #SetupWizard
        #com.google.android.dialer.support
    )
    echo "Removing unnecessary apps from Google..."
    for item in "${debloatfiles[@]}"; do
        echo " > $item"
        sed -i "/$item/d" $debloatmkfile > /dev/null 2>&1
        rmlines $debloatbpfile $item android_app_import
    done
    sleep 5
}

function undodebloat(){ # To avoid issues when repo sync
    rm $debloatmkfile
    mv $debloatmkfilebkp $debloatmkfile
    rm $debloatbpfile
    mv $debloatbpfilebkp $debloatbpfile
}

function materialfiles(){
    local workingfolder="$derpfestfolder/vendor/app/MaterialFiles"
    local apk="MaterialFiles.apk"
    if [ ! -d $workingfolder ]; then mkdir $workingfolder; fi
    cd $workingfolder
    echo
    if [ -f $apk ]; then
        echo "MaterialFiles.apk found, removing and downloading again"
        rm $apk
    fi
    echo "Getting MaterialFiles apk..."
    curl -s https://api.github.com/repos/zhanghai/materialFiles/releases/latest | grep "browser_download_url" | grep "universal" | cut -d : -f 2,3 | tr -d \" | wget -qi -
    mv *.apk $apk
    cd $rootfolder
}

function helpmsg(){
    echo "Script to build DerpFest for Google Pixel 7 series"
    echo
    echo "Usage:"
    echo " -d, --device <device> Specifies the device to build for (panther, cheetah, lynx or all)."
    echo " -j, --jobs <jobs>     Specifies the maximum jobs when compiling."
    echo "                       If not supplied, all processor threads will be used."
    echo " -s, --sync-derp       Downloads DerpFest sources."
    echo " -r, --root            Creates Sultan Wild Kernel for the selected device."
    echo " -p, --poweroff        Determines whether the computer should be turned off when finished."
    echo
    exit 1
}

# Using getopt for handling options
OPTIONS=$(getopt -o d:j:spr -l device:,jobs:,sync-derp,poweroff,root -- "$@")
eval set -- "$OPTIONS"

while true; do
    case "$1" in
        -d|--device)
            device="$2"
            shift 2
            ;;
        -s|--sync-derp)
            syncderp=true
            shift
            ;;
        -p|--poweroff)
            poweroff=true
            shift
            ;;
        -j|--jobs)
            jobs="$2"
            shift 2
            ;;
        -r|--root)
            root=true
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

if [ -z $jobs ]; then jobs=$(nproc --all); fi

if [ $syncderp = true ]; then
    bash $banner_script nowait $device $android_version $los_branch
    echo -e "${WHITEONBLUE} Syncing DerpFest                  ${NOCOLOR}"
    if [ ! -d $derpfestfolder ]; then
        mkdir $derpfestfolder
        cd $derpfestfolder
        repo init -u "$derp_repo""android_manifest.git" -b $derp_branch --git-lfs
        git clone $local_manifest_url $local_manifest_folder
        if [ ! -d ".repo/local_manifests" ]; then mkdir ".repo/local_manifests"; fi
        cp $local_manifest_file .repo/local_manifests/
    else
        cd $derpfestfolder
    fi
    repo sync --force-sync
    sleep 5
fi

cd $rootfolder

case "$device" in
    "all")
        bash $banner_script nowait $device $android_version $los_branch
        #materialfiles
        debloat
        builddevice panther
        if [ $ERROR = true ]; then continue; fi
        if [ $root = true ]; then rootdevice panther; fi
        builddevice cheetah
        if [ $ERROR = true ]; then continue; fi
        if [ $root = true ]; then rootdevice cheetah; fi
        builddevice lynx
        if [ $ERROR = true ]; then continue; fi
        if [ $root = true ]; then rootdevice lynx; fi
        ;;
    "panther" | "cheetah" | "lynx" )
        bash $banner_script nowait $device $android_version $los_branch
        #materialfiles
        debloat
        builddevice $device
        if [ $ERROR = true ]; then continue; fi
        if [ $root = true ]; then rootdevice $device; fi
        ;;
    *)
        echo
        echo -e "${RED} What device to build?${NOCOLOR}"
        echo
        helpmsg
        exit 1
        ;;
esac


# Cleaning
echo -e "${WHITEONBLUE} Cleaning...                       ${NOCOLOR}"
if [ -f $debloatmkfilebkp ] || [ -f $debloatbpfilebkp ]; then
    echo "Undoing debloat.."
    undodebloat
fi
echo "Removing temp files..."
cleaning_files=()
for i in "${cleaning_files[@]}"; do
    rm $i
done

bash $banner_script nowait $1 $android_version $los_branch

if [ $ERROR = true ]; then
    echo -e "${WHITEONRED} BUILD ERROR          ${NOCOLOR}"
    echo -e "${RED} Something went wrong during build. ${NOCOLOR}"
    echo -e "${RED} Check logs and try again. ${NOCOLOR}"
else
    echo -e "${WHITEONCYAN} BUILD COMPLETE          ${NOCOLOR}"
fi


elapsed_time=$SECONDS # Timer tick
secs=$((elapsed_time % 60))
mins=$(( (elapsed_time % 3600) / 60 ))
hours=$((elapsed_time / 3600))
if [ $secs -lt 10 ]; then secs="0$secs"; fi
if [ $mins -lt 10 ]; then mins="0$mins"; fi
if [ $hours -lt 10 ]; then hours="0$hours"; fi

echo -e "${YELLOW}┌──────────────────┐${NOCOLOR}"
echo -e "${YELLOW}│ ${CYAN}Time spent:      ${YELLOW}│${NOCOLOR}"
echo -e "${YELLOW}│ ${WHITEONMAGENTA} "$hours"h "$mins"m "$secs"s ${NOCOLOR}    ${YELLOW}│${NOCOLOR}"
echo -e "${YELLOW}└──────────────────┘${NOCOLOR}"


if [ $poweroff = true ]; then
    timer=10
    timercolor=""
    echo -e "${WHITEONMAGENTA}Switching off computer in $timer seconds        ${NOCOLOR}"
    for (( i = $timer; i >= 0; i-- )); do
        if [ $i != 0 ]; then
            if [ $(($timer/$i)) = 1 ]; then timercolor=${GREEN}; fi
            if [ $(($timer/$i)) = 2 ]; then timercolor=${YELLOW}; fi
            if [ $(($timer/$i)) = 3 ]; then timercolor=${RED}; fi
            echo -ne "$timercolor████${NOCOLOR}"
        else
            echo -ne "${RED}████${NOCOLOR}"
        fi
        sleep 1
    done
    echo
    systemctl poweroff
fi
