#!/bin/bash

syncderp=false
synckernel=false
poweroff=false
root=false
device=""
jobs=""
kernelversion="6.1"
rootfolder=`pwd`
kernelsrcfolder=$rootfolder"/googlekernel"
derpfestfolder=$rootfolder"/derpfest"
kernelfiles=true
gcam="MGC_9.4.103_V20"
gcamhash="f64522e646e8cbebe503a5ce1eefb60e1596ae45fa5732dfc5f3569d717c91fb"
debloatmkfile=$derpfestfolder/vendor/google/gms/gms-vendor.mk
debloatmkfilebkp=$debloatmkfile.bak
debloatbpfile=$derpfestfolder/vendor/google/gms/Android.bp
debloatbpfilebkp=$debloatbpfile.bak

function banner() {
    clear
    echo "▓█████▄ ▓█████  ██▀███   ██▓███    █████▒▓█████   ██████ ▄▄▄█████▓"
    echo "▒██▀ ██▌▓█   ▀ ▓██ ▒ ██▒▓██░  ██▒▓██   ▒ ▓█   ▀ ▒██    ▒ ▓  ██▒ ▓▒"
    echo "░██   █▌▒███   ▓██ ░▄█ ▒▓██░ ██▓▒▒████ ░ ▒███   ░ ▓██▄   ▒ ▓██░ ▒░"
    echo "░▓█▄   ▌▒▓█  ▄ ▒██▀▀█▄  ▒██▄█▓▒ ▒░▓█▒  ░ ▒▓█  ▄   ▒   ██▒░ ▓██▓ ░ "
    echo "░▒████▓ ░▒████▒░██▓ ▒██▒▒██▒ ░  ░░▒█░    ░▒████▒▒██████▒▒  ▒██▒ ░ "
    echo " ▒▒▓  ▒ ░░ ▒░ ░░ ▒▓ ░▒▓░▒▓▒░ ░  ░ ▒ ░    ░░ ▒░ ░▒ ▒▓▒ ▒ ░  ▒ ░░   "
    echo " ░ ▒  ▒  ░ ░  ░  ░▒ ░ ▒░░▒ ░      ░       ░ ░  ░░ ░▒  ░ ░    ░    "
    echo " ░ ░  ░    ░     ░░   ░ ░░        ░ ░       ░   ░  ░  ░    ░      "
    echo "   ░       ░  ░   ░                         ░  ░      ░           "
    echo " ░                                                                "
    echo
}

function gcam() { # Change Google Camera for GCam by BSG
    banner
    echo -e "\e[1;37;44m MOD: GCAM by BSG                  \e[0m"
    echo
    echo "- Checking Google Camera..."
    camerafolder="$derpfestfolder/vendor/google/camera/proprietary/product/priv-app/GoogleCamera"
    camerafile="GoogleCamera.apk"
    bsgcamera="MGC_9.4.103_V20_MGC.apk"
    if [ ! -f "$camerafolder/$camerafile" ] || [ $(sha256sum "$camerafolder/$camerafile" | cut -d ' ' -f 1) != $gcamhash ]; then
        echo -e "\e[33mBSG Gcam not found\e[0m"
        echo
        echo "- Checking ROM tree..."
        for file in `find | grep $camerafile`; do
            echo $file
            rm $file
        done
        if [ -f $bsgcamera ]; then rm $bsgcamera; fi
        echo "Downloading GCAM from celzoazevedo.com..."
        wget -nv --show-progress https://1-dontsharethislink.celsoazevedo.com/file/filesc/$bsgcamera
        echo "Checking hash..."
        if [ $(sha256sum $bsgcamera | cut -d ' ' -f 1) = $gcamhash ]; then
            echo -e "\e[32mBSG Cam OK\e[0m"
            echo "Copying to ROM tree..."
            mv $bsgcamera "$camerafolder/$camerafile"
        else
            echo "Couldn't download!!"
        fi
    else
        echo -e "\e[32mGCAM from BSG found\e[0m"
    fi
    sleep 3
}


function builddevice() {
    # gcam Module deactivated due to errors when starting up
    banner
    echo -e "\e[1;37;44m Device: $1                        \e[0m"
    #checkernel $1 Module deactivated due to move to LineageOS kernel sources
    cd $derpfestfolder
    echo
    echo "- Building ROM with $jobs simultaneous processes..."
    echo "Process started at `date`"
    SECONDS=0
    konsole -e "bash -c '. build/envsetup.sh && lunch lineage_$1-bp2a-user && export RELAX_USES_LIBRARY_CHECK=true && mka derp -j $jobs && sleep 5 && exit; bash'"
    elapsed_time=$SECONDS
    printf "Elapsed time: %02d:%02d:%02d\n" $((elapsed_time / 3600)) $(( (elapsed_time % 3600) / 60 )) $((elapsed_time % 60))

    #move files to more accessible folder
    mkdir -p 00_latest_builds/$1
    files=(DerpFest*.zip DerpFest*.sha256sum boot.img dtbo.img init_boot.img vendor_boot.img vendor_kernel_boot.img)
    for item in "${files[@]}"; do
        mv out/target/product/$1/$item 00_latest_builds/$1/
    done

    sleep 5
    echo
}

function rootdevice(){
    echo -e "\e[1;37;44m Rooting: $1                       \e[0m"
    cd $derpfestfolder/00_latest_builds/$1/
    if [ ! -f boot.img ]; then
        echo -e "\e[1;31mboot.img not found for $1\e[0m"
        return
    fi

    local rootfolder=`pwd`"/root"
    if [ -d "$rootfolder" ]; then rm -rf "$rootfolder"; fi
    mkdir $rootfolder
    cd $rootfolder

    echo
    echo "Getting magiskboot..."
    curl -s https://api.github.com/repos/topjohnwu/magisk/releases/latest | grep "browser_download_url.*apk" | cut -d : -f 2,3 | tr -d \" | wget -qi -
    unzip Magisk*.apk lib/x86_64/libmagiskboot.so
    mv $(find | grep libmagiskboot.so) magiskboot
    rm -rf lib
    rm *.apk
    chmod +x magiskboot

    echo
    echo "Getting Sultan Wild Kernel..."
    curl -s https://api.github.com/repos/WildKernels/Sultan_KernelSU_SUSFS/releases/latest | grep "browser_download_url.*gs201" | cut -d : -f 2,3 | tr -d \" | wget -qi -
    sultanfile="$(ls *gs201*WKSU*.zip)"
    if [ -f $sultanfile ]; then
        unzip $sultanfile Image.lz4
    else
        echo "Sultan Wild Kernel not found. Download it and try again"
        return
    fi

    echo
    echo "Unpacking original boot.img..."
    cp ../boot.img boot.img
    ./magiskboot unpack boot.img
    echo
    echo "Modifying kernel..."
    mv -f Image.lz4 kernel
    echo
    echo "Repacking kernel..."
    ./magiskboot repack boot.img
    mv new-boot.img boot_$1_WKSU_SUSFS.img
    rm kernel magiskboot $sultanfile boot.img

    echo
    echo "Getting Sultan Wild root manager..."
    curl -s https://api.github.com/repos/WildKernels/Wild_KSU/releases/latest | grep "browser_download_url" | cut -d : -f 2,3 | tr -d \" | wget -qi -
}

function rmlines(){ # file, key_pattern, end_pattern
    local tempfile="temp.bp"
    local line_number1=0
    local line_number2=0
    local line_number3=0
    local found_line1=0
    local found_line2=0
    local start=0
    local end=0

    while IFS= read -r line; do
        line_number1=$((line_number1 + 1))

        if [[ "$line" == *"$2"* ]]; then
            found_line1=$line_number1
            break
        fi
    done < "$1"

    while IFS= read -r line; do
        line_number2=$((line_number2 + 1))

        if [[ "$line" == *"$3"* ]]; then
            if [ "$line_number2" -lt "$found_line1" ]; then
                continue
            else
                found_line2=$line_number2
                break
            fi
        fi
    done < "$1"

    start=$(($found_line1 - 1))
    end=$(($found_line2 - 1))

    line_number=0

    while IFS= read -r line; do
        line_number3=$((line_number3 + 1))

        if (( line_number3 < start || line_number3 > end )); then
            echo "$line" >> "$tempfile"
        fi
    done < "$1"

    mv "$tempfile" "$1"
}

function debloat(){
    echo -e "\e[1;37;44m Debloating...                     \e[0m"
    cp "$debloatmkfile" "$debloatmkfilebkp"
    cp "$debloatbpfile" "$debloatbpfilebkp"
    local debloatfiles=(        # Comment to keep in ROM
        #GoogleExtShared
        GooglePrintRecommendationService
        #GooglePackageInstaller
        TagGoogle
        CalculatorGoogle
        CalendarGoogle
        #Chrome64
        Drive
        Gemini
        Gmail2
        #GoogleContacts
        GoogleLocationHistory
        #LatinImeGoogle
        Maps
        Photos
        #SpeechServicesByGoogle
        #TrichromeLibrary64
        #WebViewGoogle64
        YouTube
        talkback
        #AndroidAutoStub
        #ConfigUpdater
        #CrossDeviceServices
        #DeskClockGoogle
        FamilyLinkParentalControls
        #FilesGoogle
        #GWP
        #GmsCore
        #AndroidPlatformServices
        #GoogleDialer
        #GoogleOneTimeInitializer
        #GooglePartnerSetup
        #GoogleRestore
        #Messages
        PersonalSafety
        #Phonesky
        #Turbo
        #Velvet
        Wellbeing
        EmergencyInfoGms
        GoogleFeedback
        #GoogleServicesFramework
        #SetupWizard
        #com.google.android.dialer.support
    )
    echo "Removing unnecessary apps from Google..."
    for item in "${debloatfiles[@]}"; do
        echo " > $item"
        sed -i "/$item/d" $debloatmkfile > /dev/null 2>&1
        rmlines $debloatbpfile $item android_app_import
    done
    sleep 5
}

function undodebloat(){ # To avoid issues when repo sync
    rm $debloatmkfile
    mv $debloatmkfilebkp $debloatmkfile
    rm $debloatbpfile
    mv $debloatbpfilebkp $debloatbpfile
}

function helpmsg(){
    echo "Script to build DerpFest for Google Pixel 7 series"
    echo
    echo "Usage:"
    echo " -d, --device <device> Specifies the device to build for (panther, cheetah, lynx or all)."
    echo " -j, --jobs <jobs>     Specifies the maximum jobs when compiling."
    echo "                       If not supplied, all processor threads will be used."
    echo " -s, --sync-derp       Downloads DerpFest sources."
    echo " -r, --root            Creates Sultan Wild Kernel for the selected device."
    echo " -p, --poweroff        Determines whether the computer should be turned off when finished."
    echo
    exit 1
}

# Using getopt for handling options
OPTIONS=$(getopt -o d:j:spr -l device:,jobs:,sync-derp,poweroff,root -- "$@")
eval set -- "$OPTIONS"

while true; do
    case "$1" in
        -d|--device)
            device="$2"
            shift 2
            ;;
        -s|--sync-derp)
            syncderp=true
            shift
            ;;
        -p|--poweroff)
            poweroff=true
            shift
            ;;
        -j|--jobs)
            jobs="$2"
            shift 2
            ;;
        -r|--root)
            root=true
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

if [ -z $jobs ]; then jobs=$(nproc --all); fi

if [ $syncderp = true ]; then
    banner
    echo
    echo -e "\e[1;37;44m Syncing DerpFest                  \e[0m"
    if [ ! -d $derpfestfolder ]; then
        mkdir $derpfestfolder
        cd $derpfestfolder
        repo init -u https://github.com/DerpFest-AOSP/android_manifest.git -b 16 --git-lfs
    else
        cd $derpfestfolder
    fi
    konsole -e "bash -c 'repo sync --force-sync && sleep 5 && exit; exec bash'"
fi

cd $rootfolder

case "$device" in
    "all")
        banner
        debloat
        builddevice panther
        if [ $root = true ]; then rootdevice panther; fi
        builddevice cheetah
        if [ $root = true ]; then rootdevice cheetah; fi
        builddevice lynx
        if [ $root = true ]; then rootdevice lynx; fi
        ;;
    "panther" | "cheetah" | "lynx" )
        banner
        debloat
        builddevice $device
        if [ $root = true ]; then rootdevice $device; fi
        ;;
    *)
        echo
        echo -e "\e[1;31mFAIL!! What device to build?\e[0m"
        echo
        helpmsg
        exit 1
        ;;
esac

if [ -f $debloatmkfilebkp ] || [ -f $debloatbpfilebkp ]; then undodebloat; fi

if [ $poweroff = true ]; then systemctl poweroff; fi
